/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@interface SBAlertDisplay (PhoneNumberResolution)
+ (id)imageForPerson:(void *)arg1 display:(id)arg2 isFullscreen:(char *)arg3;
@end i phone 4s #hack details nawversions:
  fpt: '*'
  ghes: '>3.1'
  ghae: '*'

